version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: ubuntu:latest  # You can choose any other image that fits your needs
    resource_class: small
    steps:
      - run: |
          apt-get update && \
          apt-get install -y wget unzip && \
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip && \
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip && \
          mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner && \
          echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc && \
          source ~/.bashrc
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar Branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - say-hello
